### PR TITLE
remaned to LineLoginButton,Line LoginButtonDelegate

### PR DESCRIPTION
**Pull request by Yusuke-Yamauchi**

### CODE REVIEW

**Comment by onevcat** [comment]
Thanks for this. But this kind of API breaking change cannot be merged. I am not sure about the reason why you want to rename these, but if there is a conflicting with your current project, you may prefix `LineSDK` to the class name to help the compiler to know which type you want to use. Eg: `LineSDK.LoginButton`.

**Comment by Yusuke-Yamauchi** [comment]
Reason is that it was using the same name as Facebook Login SDK. I would appreciate it if it changes.

**Comment by onevcat** [comment]
Sorry to hear that. But no, since it is already a public one so we cannot change it now. You may need to prefix the framework name to differentiate these two.

I suggest you can add a typealias yourself to make things easier:

```swift
typealias LineLoginButton = LineSDK.LoginButton
```

**Comment by Yusuke-Yamauchi** [comment]
thank you  for the advice!

**Pull request closed without merging**
